name       : icmake
version    : 9.02.08
release    : 3
source     :
    - https://gitlab.com/fbb-git/icmake/-/archive/9.02.08/icmake-9.02.08.tar.bz2 : 92770da94469310fa2118b219d526967e3e992751107b569574abc911132ce3b
license    : GPL-3.0-or-later
component  : system.utils
summary    : Icmake is a hybrid between a 'make' utility and a 'shell script' language
description: |
    Icmake is a hybrid between a 'make' utility and a 'shell script'
build      : |
    pushd icmake
    ./icm_prepare /
    ./icm_bootstrap /
    popd
install    : |
    pushd icmake
    ./icm_install all %installroot%
    popd
