name       : icmake
version    : 9.03.01
release    : 4
source     :
    - https://gitlab.com/fbb-git/icmake/-/archive/9.03.01/icmake-9.03.01.tar.gz : 7c5c091f58f576da580238c5e3636e2038d9ecf5efb6562ae7e402910d9036e6
homepage   : https://fbb-git.gitlab.io/icmake/
license    : GPL-3.0-or-later
component  : system.utils
summary    : Icmake is a make utility using a C-line grammar
description: |
    Icmake can be used as an alternative to make(1). Icmake allows the programmer to use a program language (closely resembling the well-known C-programming language) to define the actions involved in (complex) program maintenance. For this, icmake offers various special operators as well as a set of support functions that have proven to be useful in program maintenance.
build      : |
    pushd icmake
    ./icm_prepare /
    ./icm_bootstrap /
    popd
install    : |
    pushd icmake
    ./icm_install all %installroot%
    popd

    rm -r $installdir/usr/share/doc
