name       : icmake
version    : 7.22.01
release    : 1
source     :
    - http://internode.dl.sourceforge.net/project/icmake/icmake/7.22.01/icmake_7.22.01.orig.tar.gz : b522e7937e9d4f0bec738dfce371673e3c4a8bc9f4d209a51631e5ed59ba66c7
license    : GPL-3.0
summary    : Icmake is a hybrid between a 'make' utility and a 'shell script' language
description: |
    Icmake is a hybrid between a 'make' utility and a 'shell script'
build      : |
    ./icm_bootstrap /
install    : |
    ./icm_install all %installroot%
